global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:8080']

  - job_name: 'file-ingestion-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['file-ingestion-service:8080']

  - job_name: 'soap-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['soap-service:8080']

  - job_name: 'rest-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rest-service-1:8080', 'rest-service-2:8080']

  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'spring-visualizer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-visualizer:8080']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'consul'
    metrics_path: '/v1/agent/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['consul:8500']
